---
- name: Checking vars tasks
  import_tasks: check-vars.yml

- name: Include setup tasks (requires user with root rights in order to run)
  include: setup.yml
  when:
    - ansible_user_id == "root"
    - not kafka_disable_install
    - not ansible_check_mode

- include: config.yml
  when:
    - ansible_user_id == "root"
    - kafka_create_config | bool
    - not kafka_disable_install or kafka_instaled
    - not ansible_check_mode or kafka_instaled

- name: Ensure kafka is started and enabled at boot.
  service:
    name: kafka
    state: started
    enabled: "{{ kafka_enabled_on_boot }}"
  when:
    - ansible_user_id == "root"
    - not kafka_disable_install or kafka_instaled
    - not ansible_check_mode